### ISSUE TITLE
Can we get the jVectorMapKibanaCountry plugin for Kibana 5.3 please?

### ISSUE THREAD

**Issue by neilc2016** [snuids/Elastic-5.0-Country-Map-Visualizer#8]
Can we get the jVectorMapKibanaCountry plugin for Kibana 5.3 please?

Saved Visualization Service: Visualization type of "jVectorMapCountry" is invalid. Please change to a valid type.

**Comment by vram001** [comment]
+1
Plugin is not work for V5.3, same msg as @neilc2016 
Saved Visualization Service: Visualization type of "jVectorMapCountry" is invalid. Please change to a valid type.

**Comment by snuids** [comment]
I am using it with Kibana 5.4 without any problem. Do you run Kibana via docker ? You can force the plugin reloading by changing the version of the plugin in the package.json file from "kibana" to "5.3" if this is the version you use. 

Example:
{	
	"name": "jvectormapcountry",
	"version": "5.3"
}

Restart kibana and check in the kibana logs if everything is loaded properly.

I have a full docker ELK 5.4 working stack via docker-compose here (https://mannekentech.com/2017/05/06/elk-5-4-released/).

If you use Docker and the 5.3 stack, this container works for me.
https://hub.docker.com/r/snuids/elk-kib-nox-add2/tags/
=> snuids/elk-kib-nox-add2:v5.3.0

**Comment by neilc2016** [comment]
It turns out we had to recreate the visualizations with jvectormapcountry.  For some reason after upgrading form Kibana/Elastic 2.x to 5.x visualizations did not work.
