### ISSUE TITLE
Adding two maps in one dashboard

### ISSUE THREAD

**Issue by TRISAF** [snuids/Elastic-5.0-Country-Map-Visualizer#9]
Hi,
while adding a second offline-map in a dashboard make the second not appearing.
 But in console i have no errors to attach.
As you can see in the image , when i select a country in top map, the counter of hits appears in the second map ...

How we can fix this?

![jvectormap_error](https://user-images.githubusercontent.com/22656565/27601572-1a2ce15a-5b70-11e7-8554-dbab960bc5d9.png)

**Comment by snuids** [comment]
Will try to have a look. I noticed that on my own dashboards.

**Comment by TRISAF** [comment]
Hi snuids, do you have any news?

**Comment by snuids** [comment]
It looks like I need to generate html on the fly, because I am using a fixed ID for the map div. As this kind of map is now included in Elastic 5.5. I don't think that it is worth the work.

**Comment by snuids** [comment]
I also describe in my blog how to configure the region map system in Kibana 5.5.
